RUN apt-get install curl
RUN mkdir /software/rust && cd /software/rust && \
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.rs && \
	chmod +x rustup.rs && \
	./rustup.rs -y
	
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

RUN mkdir /software/FCLQC && cd /software/FCLQC && \
	git clone https://github.com/Minhyeok01/FCLQC.git && \
	cd /software/FCLQC/FCLQC && $HOME/.cargo/bin/cargo run --release