#!/bin/bash

#SBATCH -n 32
#SBATCH -N 1
#SBATCH --partition=short
##SBATCH --partition=priority-mem768 
#SBATCH --qos=maizegdb
#SBATCH --mem=150G
#SBATCH --time=1-00:00:00
#SBATCH --job-name="testing"
#SBATCH --mail-user=sagnikbanerjee15@gmail.com
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/ABRIDGE/exhaustive_testing.output
#SBATCH --error=/project/maizegdb/sagnik/ABRIDGE/exhaustive_testing.error

module load singularity
module load python_3/3.9.2

/project/maizegdb/sagnik/ABRIDGE/Abridge/perform_exhaustive_testing