#!/bin/bash

#SBATCH -n 1
#SBATCH -N 1
#SBATCH --partition=long
##SBATCH --partition=priority-mem768 
#SBATCH --qos=maizegdb
#SBATCH --mem=150G
#SBATCH --time=2-00:00:00
#SBATCH --job-name="testing"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/ABRIDGE/exhaustive_testing.output
#SBATCH --error=/project/maizegdb/sagnik/ABRIDGE/exhaustive_testing.error

module load singularity
module load python_3/3.9.1

python /project/maizegdb/sagnik/ABRIDGE/Abridge/perform_exhaustive_testing